[package]
name = "nonet"
version = "0.1.0"
edition = "2021"
description = "Establishes a feature convention and tests that 'the internet' is accessible."
license = "Apache-2.0"
homepage = "https://github.com/holochain/holochain"
documentation = "https://docs.rs/nonet"

[dependencies]
reqwest= "0.11"
tokio = { version = "1.27", features = ["full"] }
anyhow = "1"

[features]

nonet = []
